apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: gpsplit
type: Opaque
data:
  mysql-root-password: cm9vdA==
  mysql-user: Z3BzX3VzZXI=
  mysql-password: Z3BzX3Bhc3M=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: gpsplit
data:
  MYSQL_DATABASE: gpsplit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: gpsplit
spec:
  selector:
    matchLabels: { app: mysql }
  template:
    metadata:
      labels: { app: mysql }
    spec:
      containers:
        - name: mysql
          image: mysql:8
          ports: [ {containerPort: 3306} ]
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom: {secretKeyRef: {name: mysql-secret, key: mysql-root-password}}
            - name: MYSQL_DATABASE
              valueFrom: {configMapKeyRef: {name: mysql-config, key: MYSQL_DATABASE}}
            - name: MYSQL_USER
              valueFrom: {secretKeyRef: {name: mysql-secret, key: mysql-user}}
            - name: MYSQL_PASSWORD
              valueFrom: {secretKeyRef: {name: mysql-secret, key: mysql-password}}
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: gpsplit
spec:
  selector: { app: mysql }
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql
  type: ClusterIP
