apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gpsplit-backend-ingress
  namespace: gpsplit
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - muict.app
      secretName: muict-app-tls
  rules:
    - host: muict.app
      http:
        paths:
          - path: /<group-name>-frontend(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: <group-name>-frontend-service
                port:
                  number: 80
