name: gadypadieclinic
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.10
  webview_flutter: ^3.0.4
  shared_preferences: ^2.2.0
  intl: ^0.20.0
  cupertino_icons: ^1.0.8
  table_calendar: ^3.2.0
  http: ^1.3.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.0





  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/image/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/image/gadypadiestore.png
    - assets/image/logo.png
    - assets/image/promotion.png
    - assets/image/reviews1.png
    - assets/image/reviews2.PNG
    - assets/image/reviews3.PNG
    - assets/image/reviews4.PNG
    - assets/image/reviews5.PNG
    - assets/image/reviews6.PNG
    - assets/image/reviews7.PNG
    - assets/image/reviews8.PNG
    - assets/image/servicesimage1.png
    - assets/image/servicesimage2.png
    - assets/image/servicesimage3.png
    - assets/image/servicesimage4.png
    - assets/image/servicesimage5.png
    - assets/image/servicesimage6.png
    - assets/image/servicesimage7.png
    - assets/image/3.png
    - assets/image/4.png
    - assets/image/5.png
    - assets/image/6.png
    - assets/image/7.png
    - assets/image/8.png
